spring.profiles.active=dev
spring.application.name=bux-buddy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.messages.basename=messages
spring.messages.encoding=UTF-8

server.port=${PORT:8080}