#spring.datasource.url=jdbc:mysql://localhost:3306/bux_buddy?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=Namitha@1983


spring.datasource.url=jdbc:sqlserver://SQL1002.site4now.net:1433;databaseName=db_ab1edf_buxbuddy;encrypt=true;trustServerCertificate=true
spring.datasource.username=db_ab1edf_buxbuddy_admin
spring.datasource.password=Naveen@2000

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=DevSecretKey
jwt.expiration=86400000

app.cors.allowed-origins=http://localhost:5173